# Generated by Django 2.2 on 2021-10-30 03:10

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
    ]
